\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

\title{Effect of Rapamycin on Expression of Differentiation Markers}
\maketitle

<<data-entry, echo=FALSE>>=
input_file <- 'qRT-PCR combined data.csv'
#import our data
data <- read.csv(input_file)

genes.of.interest <- c("Actb","Cdkn1a","Mef2c","Myf5","Myod1","Myog" )
#remove genes that we are not interested in
data.of.interest <- droplevels(subset(data, gene %in% genes.of.interest))
data.of.interest$Rapamycin <- grepl("RAPA", data.of.interest$treatment)
@

This uses the input file \Sexpr{input_file}.  This is located in \verb+\Sexpr{getwd()}+.  It was most recently run on \Sexpr{date()}.

First we did an ANOVA looking at all of the genes, treatments and experiments together.  These results are shown below:

<<anova, echo=FALSE>>=
#run a one-way anova on all treatment groups from each experiment to see if they vary
treatment.aov <- aov(value~gene * treatment*Exp, data=data.of.interest)
#because there is an interaction among all of the variables we need to perform a two way anova for each experiment seperately looking at effect of treatment and gene
summary(treatment.aov)
@

Since we saw an interaction between the experiment and gene and treatment terms we separated out the experiments and did 2-way ANOVA analyses on each.  These results are below:

<<statistics, echo=FALSE>>=
print('feb28 plate 2')
summary(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='feb28 plate 2')))
print('mar7 plate 2')
summary(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='mar7 plate 2')))
print('Mar7 plate1')
summary(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='Mar7 plate1')))
print('dose response ')
summary(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='dose response ')))
print('20-Feb')
summary(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='20-Feb')))
@


\section*{Testing ANOVA Assumptions}
We next tested our ANOVA analyses for normality and equal variance by first looking at a Shapiro-Wilk test and then potentially a log-transformed Shapiro-Wilk test, followed by a Levene's Test.  Based on these results we did Student's T-Tests for each gene

<<shapiro-tests, echo=FALSE>>=
#test that the data are normally distributed
#run shapiro
print('feb28 plate 2')
shapiro.test(residuals(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='feb28 plate 2'))))
print('log transformed')
shapiro.test(residuals(aov(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='feb28 plate 2'))))
#run levene's test for equal variance 
library(car)
leveneTest(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='feb28 plate 2'))
#so the assumptions for this model are OK
print('ANOVA')
summary(aov(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='feb28 plate 2')))

#pos hoc testing for this model
print('post hoc T-test')
feb28.t.tests <- data.frame(row.names=levels(data.of.interest$gene))
for (test.gene in levels(data.of.interest$gene)) {
feb28.t.tests[test.gene,'pval'] <- t.test(log(value)~treatment, data=subset(data.of.interest, Exp=='feb28 plate 2'&gene==test.gene),  var.equal=T)$p.value
}
feb28.t.tests

print('mar7 plate 2')
shapiro.test(residuals(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='mar7 plate 2'))))
print('log tansformed')
shapiro.test(residuals(aov(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='mar7 plate 2'))))
leveneTest(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='mar7 plate 2'))
#assumptions for this model are OK
print('ANOVA')
summary(aov(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='mar7 plate 2')))

#post hoc testing for this model
print('post hoc T-test')
mar7.2.t.tests <- data.frame(row.names=levels(data.of.interest$gene))
for (test.gene in levels(data.of.interest$gene)) {
mar7.2.t.tests[test.gene,'pval'] <- t.test(log(value)~treatment, data=subset(data.of.interest, Exp=='mar7 plate 2'&gene==test.gene),  var.equal=T)$p.value
}
mar7.2.t.tests


#
print('Mar7 plate1')
shapiro.test(residuals(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='Mar7 plate1'))))
print('no need for log transform')
leveneTest(value~gene*treatment, data=subset(data.of.interest, Exp=='Mar7 plate1'))
#assumptions for this model are OK (no log transform needed)
print('ANOVA')
summary(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='Mar7 plate1')))
#post hoc testing for this model
print('post hoc T-test')
mar7.1.t.tests <- data.frame(row.names=levels(data.of.interest$gene))
for (test.gene in levels(data.of.interest$gene)) {
mar7.1.t.tests[test.gene,'pval'] <- t.test(value~treatment, data=subset(data.of.interest, Exp=='Mar7 plate1'&gene==test.gene), var.equal=T)$p.value
}
mar7.1.t.tests

print('20-Feb')
shapiro.test(residuals(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='20-Feb'))))
print('log transformed')
shapiro.test(residuals(aov(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='20-Feb'))))
leveneTest(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='20-Feb'))
#assumptions for this model are OK
print('ANOVA')
summary(aov(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='20-Feb')))

#pos hoc testing for this model
print('post hoc T-test')
feb20.t.tests <- data.frame(row.names=levels(data.of.interest$gene))
for (test.gene in levels(data.of.interest$gene)) {
feb20.t.tests[test.gene,'pval'] <- t.test(log(value)~treatment, data=subset(data.of.interest, Exp=='20-Feb'&gene==test.gene),  var.equal=T)$p.value
}
feb20.t.tests

print('dose response ')
shapiro.test(residuals(aov(value~gene*treatment, data=subset(data.of.interest, Exp=='dose response '))))
print('log transformed')
shapiro.test(residuals(aov(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='dose response '))))
leveneTest(log(value)~gene*treatment, data=subset(data.of.interest, Exp=='dose response '))
@
Since we did not meet the assumption for equal variance we had to run a Kruskal-Wallis test instead of a normal ANOVA. We were not able to run a T-test since there are 3 groups in this experiment

<<shapiro-tests, echo=FALSE>>=
#dose response need to do anova instead of t-test due to 3 different groups
dose.response.aov <- data.frame(row.names=levels(data.of.interest$gene))

kruskal.test(value~treatment, data=subset(data.of.interest, Exp=='dose response '&gene==test.gene))$p.value
for (test.gene in  c("Actb","Mef2c","Myod1","Myog" )) {
dose.response.aov[test.gene,'pval-low'] <- t.test(mu=1, subset(data.of.interest, Exp=='dose response '&gene==test.gene& treatment=='RAPA (low)')$value)$p.value
dose.response.aov[test.gene,'pval-high'] <- t.test(mu=1, subset(data.of.interest, Exp=='dose response '&gene==test.gene& treatment=='RAPA (high)')$value)$p.value
}
dose.response.aov
@

<<summary-statistics, echo=FALSE>>=
library(plyr)
complete.experiments <- c('20-Feb','feb28 plate 2','mar7 plate 2', 'Mar7 plate1')
summary.data <- ddply(subset(data.of.interest, Exp %in% complete.experiments), .(gene, Rapamycin), summarise,
                      mean = mean(value),
                      sd = sd(value),
                      se = sd(value)/sqrt(length(value)),
                      n = length(value))

@

\begin{figure}
\begin{center}
<<label=combined-data-barplots,fig=TRUE,echo=FALSE>>=
require(reshape2)
summary.means <- dcast(summary.data, Rapamycin~gene, value.var='mean')
summary.errors <- dcast(summary.data, Rapamycin~gene, value.var='se')

plot <- barplot(as.matrix(summary.means[,2:7]), beside=T, las=1, ylab="mRNA Expression/GAPDH", ylim=c(0,2.8))
legend("topright", c("DMSO","Rapamycin"), fill=grey.colors(2), bty="n")

superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
  arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
  length = length, ...)

superpose.eb(plot, as.matrix(summary.means[,2:7]), as.matrix(summary.errors[,2:7]))
@
\end{center}
\caption{Combined Data from All Experiments}
\label{fig:combined-data-barplots}
\end{figure}


\begin{figure}
\begin{center}
<<label=separated-data-barplots,fig=TRUE,echo=FALSE>>=
par(mfrow=c(4,1))
for (experiment in complete.experiments){
  summary.data <- ddply(subset(data.of.interest, Exp ==experiment), .(gene, Rapamycin), summarise,
                      mean = mean(value),
                      sd = sd(value),
                      se = sd(value)/sqrt(length(value)),
                      n = length(value))
  summary.means <- dcast(summary.data, Rapamycin~gene, value.var='mean')
  summary.errors <- dcast(summary.data, Rapamycin~gene, value.var='se')
ymax <- max(summary.means[,3:dim(summary.means)[2]], na.rm=T) + max(summary.errors[,3:dim(summary.means)[2]], na.rm=T)
plot <- barplot(as.matrix(summary.means[,3:dim(summary.means)[2]]), beside=T, las=2, ylab="mRNA Expression/GAPDH", ylim=c(0,ymax), main=experiment)
#legend("topleft", c("DMSO","Rapamycin"), fill=grey.colors(2), bty="n")
superpose.eb(plot, as.matrix(summary.means[,3:dim(summary.means)[2]]), as.matrix(summary.errors[,3:dim(summary.means)[2]]))
}
@
\end{center}
\caption{Data for Each Experiment}
\label{fig:separated-data-barplots}
\end{figure}

\begin{figure}
\begin{center}
<<label=barplots-feb28,fig=TRUE,echo=FALSE>>=
require(reshape2)
  summary.data <- ddply(subset(data.of.interest, Exp =='feb28 plate 2'), .(gene, Rapamycin), summarise,
                      mean = mean(value),
                      sd = sd(value),
                      se = sd(value)/sqrt(length(value)),
                      n = length(value))
summary.means <- dcast(summary.data, Rapamycin~gene, value.var='mean')
summary.errors <- dcast(summary.data, Rapamycin~gene, value.var='se')

plot <- barplot(as.matrix(summary.means[,3:7]), beside=T, las=1, ylab="mRNA Expression/GAPDH", ylim=c(0,1.2))
legend("topright", c("DMSO","Rapamycin"), fill=grey.colors(2), bty="n")

superpose.eb(plot, as.matrix(summary.means[,3:7]), as.matrix(summary.errors[,3:7]))
@
\end{center}
\caption{Feb 28 Data}
\label{fig:barplots-feb28}
\end{figure}


\end{document}