\documentclass{article}

\usepackage{fullpage}
\usepackage[colorlinks=true]{hyperref}
\usepackage[tableposition=top]{caption}
\usepackage[utf8]{inputenc}

\begin{document}
\SweaveOpts{concordance=FALSE}

\title{Analysis of Birth Ratios for Double Knockout Autophagy/Raptor Crosses}
\author{Isabelle Hatfield and Dave Bridges}
\date{\today}
\maketitle


\section*{Experimental Design}

This was for the second batch of \textit{C179-Gal4} + \textit{Raptor/Tsc1} knockdown crosses.

<<data-input, echo=FALSE>>=
births_worksheet_location <- 'https://docs.google.com/spreadsheet/pub?key=0Am2qM2oZ12_jdHl2WS1NNDlWeS0zMFJxVDJSU3ZvT1E&single=true&gid=0&output=csv' 
mapping_file <- '../Data/gene_mapping.csv'
mapping.data <- read.csv(mapping_file)
mapping.data$UAS <- as.factor(mapping.data$UAS)

birth_file_name <- '../Data/Double Knockout Birth Data.csv'
download.file(births_worksheet_location, birth_file_name, method="curl")
birth_data <- read.csv(birth_file_name)
@

These data are stored in \verb+\Sexpr{getwd()}+, with the raw data saved in \verb+\Sexpr{birth_file_name}+ for the births.  This script was most recently run on \Sexpr{date()}.

\section*{24B-GAL4 Driver}

This analysis is just for the C179 Driver.

<<data-collection, echo=False>>=
birth_data$Total <- rowSums(birth_data[,6:9])
all.flies <- colSums(birth_data[,6:9])
require(plyr, quietly=T)
birth_data$Cross <- as.factor(paste(birth_data$Male, birth_data$Female, sep=" x "))
birth_data$Driver <- as.factor(sapply(strsplit(as.character(birth_data$Female), "/"),"[", 1))
birth_data$UAS.allele <- as.factor(sapply(strsplit(as.character(birth_data$Male), ","),"[", 2))
birth_data$UAS <- as.factor(sapply(strsplit(as.character(birth_data$UAS.allele), "/"),"[", 1))
#need to merge this with mappng
data <- birth_data
@

These data are stored in \verb+\Sexpr{getwd()}+, with the raw data saved in \verb+\Sexpr{birth_file_name}+.  This script was most recently run on \Sexpr{date()}

\section*{Strain Summaries}

<<data-analysis, echo=FALSE>>=
gene.summarised.data <- ddply(data, .(Driver,UAS), summarise, 
      Double_Knockdown = sum(WT),
      Raptor_Only = sum(sb),
      ATG_Only = sum(cyo),
      Wild_Type = sum(cyo.sb),
      Total = as.integer(sum(Total)))

gene.summarised.data$pval <-rep(NA, dim(gene.summarised.data)[1])
for (n in seq(1,dim(gene.summarised.data)[1])) {   
  values <- gene.summarised.data[n,3:5]
  test <- chisq.test(values, p=rep(1,3), rescale.p=T)
  gene.summarised.data[n,]$pval <- test$p.value  
}
gene.summarised.data$padj <- p.adjust(gene.summarised.data$pval, method="BH")



summarised.data.gendered <- ddply(data, .(Driver, UAS,Gender), summarise, 
      Double_Knockdown = sum(WT),
      Raptor_Only = sum(sb),
      ATG_Only = sum(cyo),
      Wild_Type = sum(cyo.sb),
      Total = as.integer(sum(Total)))

summarised.data.gendered$pval <-rep(NA, dim(summarised.data.gendered)[1])
for (n in seq(1,dim(summarised.data.gendered)[1])) {   
  values <- summarised.data.gendered[n,4:6]
  test <- chisq.test(values, p=rep(1,3), rescale.p=T)
  summarised.data.gendered[n,]$pval <- test$p.value  
}
summarised.data.gendered$padj <- p.adjust(summarised.data.gendered$pval, method="BH")


@



<<label=data-tables,echo=FALSE,results=tex>>=
require(xtable)
print(xtable(gene.summarised.data, caption="Gene Level Summarised Data", label="tab:gene_summarised_data", digits = c(rep(0,8),5,5)), include.rownames=F)
print(xtable(summarised.data.gendered, caption="Gendered Gene Level Summarised Data", label="tab:driver_summarised_data", digits = c(rep(0,9),5,5)), include.rownames=F)
@

\subsection*{Crosses with no Knockdown Progeny}

So far some crosses have produced no knockdown progeny.  These are described in Table \ref{tab:no_kd_flies}

<<label=data-tables-2,echo=FALSE,results=tex>>=
print(xtable(summarised.data.gendered[summarised.data.gendered$KD == 0,1:6], caption="Crosses with no Knockdown Flies", label="tab:no_kd_flies"))
@
\begin{figure}
\begin{center}
<<label=c179-gendered-figure,fig=TRUE,echo=FALSE>>=
#gene.summarised.data$KD.prop <- gene.summarised.data$KD/gene.summarised.data$Total
#gene.summarised.data$shRNA.prop <- gene.summarised.data$shRNA/gene.summarised.data$Total.No.WT
#gene.summarised.data$GAL4.prop <- gene.summarised.data$GAL4/gene.summarised.data$Total.No.WT

#calculated standard errors
#driver.summarised.data$KD.err <- with(driver.summarised.data, sqrt((KD.prop*(1-KD.prop)/Total.No.WT)))
#driver.summarised.data$shRNA.err <- with(driver.summarised.data, sqrt((shRNA.prop*(1-shRNA.prop)/Total.No.WT)))
#driver.summarised.data$GAL4.err <- with(driver.summarised.data, sqrt((GAL4.prop*(1-GAL4.prop)/Total.No.WT)))

par(mar=c(12,4.1,4.1,2.1))
plot <- barplot(as.numeric(gene.summarised.data[gene.summarised.data$Driver=='24B',c(3:6)]),
        las=2,
        names.arg=names(gene.summarised.data[3:6]),
        ylab="Number of Eclosed Flies",
        main="24B-Gal4 Driver")

superpose.eb <- 
 function (x, y, ebl, ebu = ebl, length = 0.08, ...) 
 arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3, 
 length = length, ...)

#superpose.eb(plot, 
#             t(as.matrix(driver.summarised.data[driver.summarised.data$Driver=="24B-Gal4",c('KD.prop','shRNA.prop','GAL4.prop')])),
#             t(as.matrix(driver.summarised.data[driver.summarised.data$Driver=="24B-Gal4",c('KD.err','shRNA.err','GAL4.err')])))
@
\end{center}
\caption{Gender Specific Differences Between C517-Gal4 Driven Raptor Knockdown Strains}
\label{fig:179-gendered}
\end{figure}

     
<<bibliography, include=F, echo=F>>=
require(bibtex)
write.bib(c(names(sessionInfo()$otherPkgs),'base','stats','utils'), file='birth-references.bib')
@

The key packages used in this analysis were R \cite{base} and plyr \cite{plyr}

\bibliography{birth-references}
\bibliographystyle{unsrt}

\section*{Session Information}
<<sessionInfo, results=tex, echo=F>>=
toLatex(sessionInfo())
@

\end{document}